.PHONY: pdf
pdf:
	mkpdf -d -p \
	-t moderncv.latex \
	-o ../users-guide.pdf \
	\
	meta.txt \
	../README.markdown \
	doc-hausarbeit.txt \
	doc-essay.txt \
	doc-letter.txt \
	doc-contract.txt \
	doc-lebenslauf.txt \
	how-to-use-variables-txt \
	general-settings.txt \
	extension-*
